# Model For Recognition And Translation Of American Sign Language 

In [13]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

In [128]:
train_df = pd.read_csv("signs\sign_mnist_train.csv")
test_df = pd.read_csv("signs\sign_mnist_test.csv")
x_train = np.array(train_df.drop(['label'], 1))
y_train = np.array(train_df['label'])
x_test = np.array(test_df.drop(['label'], 1))
y_test = np.array(test_df['label'])

In [129]:
x_train = x_train/255
x_test = x_test/255

In [137]:
x_train = np.reshape(x_train,(-1,1,28,28),order="C")
x_test = np.reshape(x_test,(-1,1,28,28),order="C")
print(x_test.shape,x_train.shape)
#plt.imshow(x_train[0])
#plt.show

(7172, 1, 28, 28) (27455, 1, 28, 28)


In [131]:
from keras.utils.np_utils import to_categorical
y_train = to_categorical(y_train)
print(y_train)
y_test = to_categorical(y_test)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [125]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [117]:
import time
from tensorflow.keras.callbacks import TensorBoard
dense_layers = [0,1,2]
layer_sizes = [64, 128, 256]
conv_layers = [1,2,3]


In [139]:
for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

            model = Sequential()

            model.add(Conv2D(layer_size, (3, 3),input_shape=(1,28,28)))
            model.add(Activation('relu'))
            model.add(MaxPooling2D(pool_size=(2, 2)))

            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3, 3)))
                model.add(Activation('relu'))
                model.add(MaxPooling2D(pool_size=(2, 2)))

            model.add(Flatten())

            for _ in range(dense_layer):
                model.add(Dense(layer_size))
                model.add(Activation('relu'))

            model.add(Dense(25))
            model.add(Activation('softmax'))

            tensorboard = TensorBoard(log_dir="logs\{}".format(NAME))

            model.compile(loss='sparse_categorical_crossentropy',
                          optimizer='adam',
                          metrics=['accuracy'],
                          )

            model.fit(x_train, y_train,
                      batch_size=64,
                      epochs=13,
                      validation_data=(x_test,y_test),
                      callbacks=[tensorboard])
            
            model.save("models\{}.h5".format(NAME))

1-conv-64-nodes-0-dense-1585767513


ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_106/Conv2D' (op: 'Conv2D') with input shapes: [?,1,28,28], [3,3,28,64].

In [ ]:



0 